name: cdx-rocks
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cdx-rocks:latest
    container_name: cdx-rocks-app
    ports:
      - "${CDX_PORT:-7860}:7860"
    volumes:
      - ./all_warc_paths.txt.zst:/app/all_warc_paths.txt.zst
      - ./rocksdb_index:/app/data
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG}
    restart: unless-stopped
